import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import SessionsProvider from "./SessionProvider";
import Header from "@/components/header";
import { getServerSession } from "next-auth/next";
import { authOptions } from "@/lib/auth";
import { UserSession } from "@/packages/types/user";



const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "FlickSphere",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(authOptions);
  return (
    <html className="dark" lang="en">
      <SessionsProvider >
      <body className={inter.className}>
        <Header user={session?.user as UserSession } />
        {children}
        </body>
      </SessionsProvider>
    </html>
  );
}
